from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from .manager import FeatureManager


class FeatureHost(Protocol):
    """Narrow host surface available to features."""

    def feature_reply(self, chat_id: int, text: str, markup: dict | None = None) -> None: ...
    def feature_main_menu(self) -> dict: ...
    def feature_system_info(self) -> str: ...
    def feature_status(self) -> str: ...
    def feature_incident_summary(self) -> str: ...
    def feature_incident_menu(self, severity: str) -> tuple[str, dict]: ...
    def feature_acknowledge_incident(self, event_id: str) -> tuple[str, dict]: ...
    def feature_open_incident_evidence(self, chat_id: int, event_id: str) -> None: ...
    def feature_edit_or_reply(self, chat_id: int, message_id: int | None, text: str, markup: dict | None = None) -> None: ...
    def feature_help(self) -> str: ...
    def feature_event(self, kind: str, detail: str, severity: str = "info") -> None: ...
    def feature_notify_owner(self, text: str, markup: dict | None = None, severity: str = "warning", kind: str = "generic") -> None: ...


class Feature(Protocol):
    """Explicit extension point; features are registered, never auto-imported."""

    name: str

    def register(self, manager: "FeatureManager") -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
