import { invoke } from "@tauri-apps/api/core";
import { enable as enableAutostart } from "@tauri-apps/plugin-autostart";
import "./styles.css";

type Locale = "fa" | "en";
type Session = { access_token: string; account_id: string };
type PairCode = { pairing_code: string; expires_at: number };
type LocalProtectionStatus = { configured: boolean; managed_local_profile: boolean; consent_recorded: boolean; armed: boolean; device_name: string; service_active: boolean };
type ManagedConnectionStatus = { state: "not_enrolled" | "connected" | "revoked" | "offline" };
const app = document.querySelector<HTMLDivElement>("#app")!;
let session: Session | null = null;
let locale: Locale = localStorage.getItem("locale") === "en" ? "en" : "fa";

const copy = {
  fa: {
    title: "انجیس‌گارد برای دسکتاپ", intro: "این دستگاه را به‌صورت امن ثبت کنید. رمز ویندوز یا لینوکس شما هرگز درخواست نمی‌شود.", language: "English", server: "نشانی سرور", email: "ایمیل", password: "رمز حساب (حداقل ۱۲ نویسه)", register: "ساخت حساب", login: "ورود", enrollTitle: "ثبت این دستگاه", enrollIntro: "برای این دستگاه نامی انتخاب کنید. اعتبار دستگاه فقط به‌صورت محلی و امن نگه‌داری می‌شود.", deviceName: "نام دستگاه", autostart: "اجرای خودکار انجیس‌گارد پس از ورود به سیستم", pair: "ثبت امن دستگاه", lock: "اجازه قفل‌کردن این نشست توسط دستور /lock ربات", botIntro: "برای پیوند گفت‌وگوی Bale یا Telegram، کد زیر را با دستور /link CODE به ربات ارسال کنید.", bot: "ساخت کد پیوند ربات", enrolled: "دستگاه ثبت شد. برنامه را باز نگه دارید تا دستورهای امن ربات دریافت شوند.", autostartSaved: "اجرای خودکار فعال شد.", lockSaved: "تنظیم قفل از راه دور فقط روی همین دستگاه ذخیره شد.", pairCode: "کد ثبت:", botCode: "کد پیوند ربات:", https: "برای سرور آزمایشی از HTTPS استفاده کنید.", error: "عملیات ناموفق بود.", divider: "پیوند ربات", connectionDivider: "اتصال به سرور مدیریت", refreshConnection: "بررسی اتصال", connectionNotEnrolled: "این دستگاه هنوز ثبت نشده است", connectionConnected: "اتصال امن به سرور برقرار است", connectionRevoked: "این دستگاه لغو شده است؛ دوباره ثبت کنید", connectionOffline: "سرور مدیریت در دسترس نیست؛ محافظت محلی ادامه دارد", protectDivider: "محافظت محلی لپ‌تاپ", protectIntro: "با تأیید شما، لپ‌تاپ‌گارد محلی آماده و اجرا می‌شود. دوربین، میکروفون، ضبط صفحه، کنترل برنامه‌ها، بازکردن قفل و خاموش‌کردن از راه دور در این حالت فعال نمی‌شوند.", consent: "می‌دانم محافظت محلی فقط با این رضایت آغاز می‌شود و قابلیت‌های خصوصی بالا غیرفعال‌اند.", startProtection: "شروع محافظت محلی", stopProtection: "توقف محافظت محلی", refreshProtection: "به‌روزرسانی وضعیت", protectionRunning: "محافظت محلی در حال اجراست", protectionStopped: "محافظت محلی متوقف است", protectionArmed: "فعال", protectionDisarmed: "غیرفعال",
  },
  en: {
    title: "AngysGuard Desktop", intro: "Enroll this device securely. Your Windows or Linux password is never requested.", language: "فارسی", server: "Server URL", email: "Email", password: "Account password (12+ characters)", register: "Create account", login: "Sign in", enrollTitle: "Enroll this device", enrollIntro: "Choose a name for this device. Its credential stays in secure local storage.", deviceName: "Device name", autostart: "Start AngysGuard automatically after I sign in", pair: "Enroll this device", lock: "Allow this device to lock its session for a bot /lock command", botIntro: "To link a Bale or Telegram chat, send the generated code to your bot as /link CODE.", bot: "Create bot link code", enrolled: "Device enrolled. Keep AngysGuard open to receive safe bot commands.", autostartSaved: "Autostart enabled.", lockSaved: "Remote-lock preference is saved only on this device.", pairCode: "Enrollment code:", botCode: "Bot link code:", https: "Use HTTPS for the test server.", error: "Operation failed.", divider: "Bot link", connectionDivider: "Managed server connection", refreshConnection: "Check connection", connectionNotEnrolled: "This device is not enrolled yet", connectionConnected: "Secure server connection is available", connectionRevoked: "This device was revoked; enroll it again", connectionOffline: "Managed server is unavailable; local protection continues", protectDivider: "Local Laptop Guard", protectIntro: "With your consent, Laptop Guard is prepared and started locally. Camera, microphone, screen recording, app control, remote unlock, and remote power stay disabled in this profile.", consent: "I understand local protection starts only with this consent and the private capabilities above remain disabled.", startProtection: "Start local protection", stopProtection: "Stop local protection", refreshProtection: "Refresh status", protectionRunning: "Local protection is running", protectionStopped: "Local protection is stopped", protectionArmed: "armed", protectionDisarmed: "disarmed",
  },
} as const;

function t(key: keyof typeof copy.fa) { return copy[locale][key]; }
function escape(value: string) { return value.replace(/[&<>"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character]!); }
function applyLocale() { document.documentElement.lang = locale === "fa" ? "fa" : "en"; document.documentElement.dir = locale === "fa" ? "rtl" : "ltr"; localStorage.setItem("locale", locale); }
function message(text: string, problem = false) { const target = document.querySelector("#message"); if (target) { target.textContent = text; target.className = problem ? "error" : "success"; } }
function switchLocale() { locale = locale === "fa" ? "en" : "fa"; applyLocale(); session ? enrollmentScreen() : loginScreen(); }
async function api<T>(path: string, init: RequestInit = {}): Promise<T> {
  const base = (document.querySelector<HTMLInputElement>("#server")?.value || localStorage.getItem("server") || "https://api.mahakaram.ir").replace(/\/$/, "");
  if (!base.startsWith("https://") && !base.startsWith("http://localhost")) throw new Error(t("https"));
  localStorage.setItem("server", base);
  const response = await fetch(`${base}${path}`, { ...init, headers: { "Content-Type": "application/json", ...(session ? { Authorization: `Bearer ${session.access_token}` } : {}), ...(init.headers || {}) } });
  if (!response.ok) throw new Error((await response.json().catch(() => ({ detail: response.statusText }))).detail || t("error"));
  return response.status === 204 ? undefined as T : response.json();
}
function languageButton() { return `<button id="language" class="secondary language" type="button" aria-label="${t("language")}">${t("language")}</button>`; }
function protectionText(status: LocalProtectionStatus) { return `${status.service_active ? t("protectionRunning") : t("protectionStopped")} · ${status.armed ? t("protectionArmed") : t("protectionDisarmed")}`; }
function connectionText(status: ManagedConnectionStatus) { return status.state === "connected" ? t("connectionConnected") : status.state === "revoked" ? t("connectionRevoked") : status.state === "offline" ? t("connectionOffline") : t("connectionNotEnrolled"); }
function loginScreen() {
  applyLocale();
  app.innerHTML = `<section><header><h1>${t("title")}</h1>${languageButton()}</header><p>${t("intro")}</p><label>${t("server")}<input id="server" value="${escape(localStorage.getItem("server") || "https://api.mahakaram.ir")}" autocomplete="url"></label><label>${t("email")}<input id="email" type="email" autocomplete="email"></label><label>${t("password")}<input id="password" type="password" minlength="12" autocomplete="new-password"></label><div class="row"><button id="register">${t("register")}</button><button id="login" class="secondary">${t("login")}</button></div><p id="message" role="status"></p></section>`;
  const authenticate = async (path: string) => { try { session = await api<Session>(path, { method: "POST", body: JSON.stringify({ email: document.querySelector<HTMLInputElement>("#email")!.value, password: document.querySelector<HTMLInputElement>("#password")!.value }) }); enrollmentScreen(); } catch (error) { message(error instanceof Error ? error.message : t("error"), true); } };
  document.querySelector("#language")!.addEventListener("click", switchLocale);
  document.querySelector("#register")!.addEventListener("click", () => authenticate("/v1/accounts"));
  document.querySelector("#login")!.addEventListener("click", () => authenticate("/v1/sessions"));
}
function enrollmentScreen() {
  applyLocale();
  app.innerHTML = `<section><header><h1>${t("enrollTitle")}</h1>${languageButton()}</header><p>${t("enrollIntro")}</p><label>${t("deviceName")}<input id="device-name" value="${escape(navigator.userAgent.includes("Windows") ? "Windows PC" : "Linux Desktop")}" maxlength="80"></label><label class="toggle"><input id="autostart" type="checkbox" checked> ${t("autostart")}</label><button id="make-device">${t("pair")}</button><p id="pair-code" class="code"></p><label class="toggle"><input id="remote-lock" type="checkbox"> ${t("lock")}</label><hr><h2>${t("connectionDivider")}</h2><button id="refresh-connection" class="secondary">${t("refreshConnection")}</button><p id="managed-connection-status" role="status"></p><hr><h2>${t("protectDivider")}</h2><p>${t("protectIntro")}</p><label class="toggle"><input id="local-consent" type="checkbox"> ${t("consent")}</label><div class="row"><button id="start-protection">${t("startProtection")}</button><button id="stop-protection" class="secondary">${t("stopProtection")}</button><button id="refresh-protection" class="secondary">${t("refreshProtection")}</button></div><p id="protection-status" role="status"></p><hr><h2>${t("divider")}</h2><p>${t("botIntro")}</p><button id="make-bot" class="secondary">${t("bot")}</button><p id="bot-code" class="code"></p><p id="message" role="status"></p></section>`;
  document.querySelector("#language")!.addEventListener("click", switchLocale);
  const showManagedConnection = async () => { const status = await invoke<ManagedConnectionStatus>("managed_connection_status"); document.querySelector("#managed-connection-status")!.textContent = connectionText(status); };
  document.querySelector("#refresh-connection")!.addEventListener("click", async () => { try { await showManagedConnection(); } catch (error) { message(error instanceof Error ? error.message : t("error"), true); } });
  document.querySelector("#make-device")!.addEventListener("click", async () => { try { const code = await api<PairCode>("/v1/devices/pairing-codes", { method: "POST", body: JSON.stringify({ device_name: document.querySelector<HTMLInputElement>("#device-name")!.value }) }); document.querySelector("#pair-code")!.textContent = `${t("pairCode")} ${code.pairing_code}`; const device = await api<{ device_id: string; device_token: string; account_id: string }>("/v1/devices/claim", { method: "POST", body: JSON.stringify({ pairing_code: code.pairing_code }) }); await invoke("store_device", { serverUrl: localStorage.getItem("server"), deviceId: device.device_id, deviceToken: device.device_token, accountId: device.account_id }); await showManagedConnection(); if (document.querySelector<HTMLInputElement>("#autostart")!.checked) { await enableAutostart(); message(t("autostartSaved")); } message(t("enrolled")); } catch (error) { message(error instanceof Error ? error.message : t("error"), true); } });
  showManagedConnection().catch(() => undefined);
  document.querySelector("#remote-lock")!.addEventListener("change", async (event) => { try { await invoke("set_remote_lock_enabled", { enabled: (event.target as HTMLInputElement).checked }); message(t("lockSaved")); } catch (error) { (event.target as HTMLInputElement).checked = false; message(error instanceof Error ? error.message : t("error"), true); } });
  const showProtectionStatus = async () => { const status = await invoke<LocalProtectionStatus>("local_protection_status"); document.querySelector("#protection-status")!.textContent = protectionText(status); };
  document.querySelector("#start-protection")!.addEventListener("click", async () => { try { const status = await invoke<LocalProtectionStatus>("prepare_local_protection", { deviceName: document.querySelector<HTMLInputElement>("#device-name")!.value, consent: document.querySelector<HTMLInputElement>("#local-consent")!.checked }); document.querySelector("#protection-status")!.textContent = protectionText(status); } catch (error) { message(error instanceof Error ? error.message : t("error"), true); } });
  document.querySelector("#stop-protection")!.addEventListener("click", async () => { try { const status = await invoke<LocalProtectionStatus>("stop_local_protection"); document.querySelector("#protection-status")!.textContent = protectionText(status); } catch (error) { message(error instanceof Error ? error.message : t("error"), true); } });
  document.querySelector("#refresh-protection")!.addEventListener("click", async () => { try { await showProtectionStatus(); } catch (error) { message(error instanceof Error ? error.message : t("error"), true); } });
  document.querySelector("#make-bot")!.addEventListener("click", async () => { try { const code = await api<PairCode>("/v1/bot-pairing-codes", { method: "POST" }); document.querySelector("#bot-code")!.textContent = `${t("botCode")} ${code.pairing_code}`; } catch (error) { message(error instanceof Error ? error.message : t("error"), true); } });
}
applyLocale();
loginScreen();
